[package]
name = "photos"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
nimble-web = { path = "../.." }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
