[package]
name = "nimble-web"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = "1"
toml = "0.8"
