[package]
name = "nimble-web"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1", features = ["derive", "std"] }
serde_json = "1"
toml = "0.8"
futures-util = "0.3"
hyper = { version = "1.8.1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["server", "tokio"] }
http-body-util = "0.1"
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "net",
    "time",
] }

[dev-dependencies]
reqwest = "0.13.1"
libc = "0.2"
